#### SPRINTS

### consultar todos los sprints
GET http://127.0.0.1:8000/sprints


### consultar sprint
GET http://127.0.0.1:8000/sprints/1


### crear sprint
POST http://127.0.0.1:8000/sprints
Content-Type: application/json

{
  "nombre": "Sprint Prueba",
  "fecha_inicio": "2026-05-01",
  "fecha_fin": "2026-05-15"
}


### modificar sprint
PUT http://127.0.0.1:8000/sprints/1
Content-Type: application/json

{
  "nombre": "Sprint Prueba1",
  "fecha_inicio": "2026-05-01",
  "fecha_fin": "2026-05-15"
}


### borrar sprint
DELETE http://127.0.0.1:8000/sprints/1




### RETRO_ITEMS

### consultar todos los items
GET http://127.0.0.1:8000/retro_items


### consultar item
GET http://127.0.0.1:8000/retro_items/1


### crear item
POST http://127.0.0.1:8000/retro_items
Content-Type: application/json

{
  "sprint_id": 2,
  "categoria": "Backend",
  "descripcion": "Implementar endpoint de autenticación",
  "cumplida": false,
  "fecha_revision": "2026-05-10"
}


### modificar item
PUT http://127.0.0.1:8000/retro_items/1
Content-Type: application/json

{
  "sprint_id": 1,
  "categoria": "Backend",
  "descripcion": "Implementar endpoint de autenticación",
  "cumplida": false,
  "fecha_revision": "2026-05-10"
}